---
- name: "[PLAY-1] PRIMER PLAY"
  hosts: localhost
  gather_facts: True
  become: no

  vars:
    variable_1: "valor_var_1"
    variable_2: "valor_var_2"

  pre_tasks:

  - ansible.builtin.assert:
      that:
        - variable_1 is defined
        - variable_1 != ""
        - variable_2 is defined
        - variable_2 != ""
      success_msg: "'VALIDATION [VARS] -> SUCCESS"

  tasks:

  - ansible.builtin.debug:
      msg: "INFO: VARIABLE 'variable_1' -> '{{ variable_1 }}'"

  - ansible.builtin.debug:
      msg: "INFO: VARIABLE 'variable_2' -> '{{ variable_2 }}'"

  - ansible.builtin.set_fact:
      variable_3: "valor_var_3"
      f_variable_4: "valor_var_4"


- name: "[PLAY-2] SEGUNDO PLAY"
  hosts: localhost
  gather_facts: True
  become: no

  vars:
    variable_5: "valor_var_5"
    variable_6: "valor_var_6"

  pre_tasks:

  - ansible.builtin.assert:
      that:
        - variable_5 is defined
        - variable_5 != ""
        - variable_6 is defined
        - variable_6 != ""
        - variable_3 is defined
        - variable_3 != ""
        - f_variable_4 is defined
        - f_variable_4 != ""
      success_msg: "'VALIDATION [VARS] -> SUCCESS"

  tasks:

  - ansible.builtin.debug:
      msg: "INFO: VARIABLE 'variable_3' -> '{{ variable_3 }}'"

  - ansible.builtin.debug:
      msg: "INFO: VARIABLE 'f_variable_4' -> '{{ f_variable_4 }}'"

  - ansible.builtin.debug:
      msg: "INFO: VARIABLE 'variable_5' -> '{{ variable_5 }}'"

  - ansible.builtin.debug:
      msg: "INFO: VARIABLE 'variable_6' -> '{{ variable_6 }}'"

...
