---
- name: Comprobar y add vlan a portchannel en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    port_id: ""
    int_id: ""
   
  # Tareas
  tasks:
    - name: Verificar existencia de configuración en portchannel
      arista.eos.eos_command:
        commands:
          - show  interfaces port-Channel {{ port_id }}
      register: port_id_check

    # Salida por pantalla
    - name: Mostrar resultado del comando show interfaces port channel id
      debug:
        msg: "{{ port_id_check.stdout }}"


    - name: Verificar existencia de configuración en interface
      arista.eos.eos_command:
        commands:
          - show run int ethernet {{ int_id }} | i channel-group {{ port_id }}
      register: int_id_check

    # Salida por pantalla
    - name: Mostrar resultado del comando show interfaces port channel id
      debug:
        msg: "{{ int_id_check.stdout }}"
     
   
    - name: eliminar port-channel con Interfaces si existe
      arista.eos.eos_command:
        commands:
          - configure terminal
          - no interface Port-channel {{ port_id }}
          - default interface Ethernet {{ int_id }}
          - interface Ethernet {{ int_id }}
          - shutdown
      when: 
          - port_id_check.stdout[0] != ''
          - int_id_check.stdout[0] != ''
      changed_when: true
        
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
