---
- name: Comprobar y crear route-map en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_route_map: ""
    nom_prefix: ""
    metric: ""
  
  # Tareas
  tasks:
    - name: Verificar existencia del route-map
      arista.eos.eos_command:
        commands:
          - show route-map {{ nom_route_map }}
      register: route-map_check

    # Salida por pantalla
    - name: Mostrar resultado del comando show vlan id
      debug:
        msg: "{{ route-map_check.stdout }}"

    - name: Crear el route map si no existe
      arista.eos.eos_config:
        lines:
          - route-map {{ nom_route_map }}
          - match ip address prefix-list {{ nom_prefix }}
          - set metric {{ metric }}
      when: "'not found' in route-map_check.stdout[0]"
    
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
        
    - name: Verificar existencia del route-map
      arista.eos.eos_command:
        commands:
          - show route-map {{ nom_route_map }}
      register: route-map_check_new

    - name: Mostrar resultado del comando show vlan id después de crear la VLAN
      debug:
        msg: "{{ 
        route-map_check_new.stdout 
        }}"

