- name: crear mpls, vrf, ospf, bgp
  hosts: all
  gather_facts: no

  vars:
    site: ""
    vlan_po: ""
    vlan_id: ""
    segmento: ""
    vrf_name: ""
    equipos_config:
      AMU-P5-E4-UR29-BLEAF-A:
        bgp_asn: "65021"
        neighbor_ip: "169.254.196.9"
        router_id: "169.254.196.9"
        id_po: "Port-Channel5."
        ip_po: "169.254.196.10/30"
      AMU-P5-E3-UR29-BLEAF-B:
        bgp_asn: "65021"
        neighbor_ip: "169.254.196.13"
        router_id: "169.254.196.13"
        id_po: "Port-Channel6."
        ip_po: "169.254.196.14/30"
      CDLV-212-G31-UR29-BLEAF-A:
        bgp_asn: "65121"
        neighbor_ip: "169.254.196.17"
        router_id: "169.254.196.17"
        id_po: "Port-Channel5."
        ip_po: "169.254.196.18/30"
      CDLV-212-G32-UR29-BLEAF-B:
        bgp_asn: "65121"
        neighbor_ip: "169.254.196.21"
        router_id: "169.254.196.21"
        id_po: "Port-Channel6."
        ip_po: "169.254.196.22/30"

  tasks:
    - name: Verificar existencia de la VRF
      arista.eos.eos_command:
        commands:
          - show vrf {{ vrf_name }}
      register: vrf_check
      ignore_errors: yes

    - name: Mostrar resultado del comando show vrf 
      debug:
        msg: "{{ vrf_check.stdout }}"

    - name: Crear la VRF si no existe
      arista.eos.eos_config:
        lines:
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }}
      when: "'{{ vrf_name }}' not in vrf_check.stdout[0]"

    - name: Configurar la interfaz para equipo CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - interface {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }} MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].ip_po }}
      when: site == 'CDLV'

    - name: Configurar la interfaz para equipo CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - interface {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }} MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].ip_po }}
      when: site == 'CDLV'

    - name: Configurar la interfaz para equipo AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - interface {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }} MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].ip_po }}
      when: site == 'AMU'

    - name: Configurar la interfaz para equipo AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - interface {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }} MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].ip_po }}
      when: site == 'AMU'

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
