- name: crear mpls, vrf, ospf, bgp, svi, route-map
  hosts: all
  gather_facts: no

  vars:
    site: ""
    vlan_id: ""
    desc: ""
    segmento: ""
    ip_publica: ""
    
  tasks:

    - name: Verificar existencia de la VLAN
      arista.eos.eos_command:
        commands:
          - show vlan id {{ vlan_id }}
      register: vlan_check

    - name: Debug VLAN check
      debug:
        var: vlan_check.stdout

    - name: Extraer la dirección base y la máscara del segmento
      set_fact:
        ip_base: "{{ segmento.split('/')[0].split('.')[:-1] | join('.') }}"
        last_octet: "{{ segmento.split('/')[0].split('.')[-1] }}"
        subnet_mask: "{{ segmento.split('/')[1] }}"

    - name: Debug IP base y máscara
      debug:
        msg:
        - "IP Base: {{ ip_base }}"
        - "Último octeto: {{ last_octet }}"
        - "Máscara de subred: {{ subnet_mask }}"
      

    - name: Calcular la primera IP disponible en el segmento
      set_fact:
        first_ip: "{{ ip_base }}.{{ last_octet | int + 1 }}"

    - name: Calcular la segunda IP disponible en el segmento
      set_fact:
        second_ip: "{{ ip_base }}.{{ last_octet | int + 2 }}"

     - name: Calcular la tercera IP disponible en el segmento
      set_fact:
        third_ip: "{{ ip_base }}.{{ last_octet | int + 3 }}"

    - name: Calcular la cuarta IP disponible en el segmento
      set_fact:
        fourth_ip: "{{ ip_base }}.{{ last_octet | int + 4 }}"
        
    - name: Mostrar las IPs calculadas
      debug:
        msg:
          - "Primera IP: {{ first_ip }}"
          - "Segunda IP: {{ second_ip }}"
          - "Tercera IP: {{ third_ip }}"
          - "Cuarta IP: {{ Fourth_ip }}"
          - "Cuarta IP: {{ fourth_ip }}"

    - name: Configurar VRRP y Ruta Estatica Publica
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vlan {{ vlan_id }}
          - name {{ desc }}-INTERNET-TDS
          - interface vlan {{ vlan_id }}
          - vrf Internet
          - ip address {{ first_ip }}/29
          - vrrp {{ vlan_id }} ip {{ third_ip }}
          - vrrp {{ vlan_id }} priority 200  
          - vrrp {{ vlan_id }} preempt
          - ip route vrf Internet {{ ip_publica }} {{ Fourth_ip }}
      when: 
        - site == 'CDLV' 
        - inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'
        - "'not found' in vlan_check.stdout[0]"
      changed_when: true

     

      
    - name: Configurar MPLS OSPF SVI ROUTE-MAP en CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          - vlan {{ vlan_id }}
          - name INTER-RED-TDS-{{ vrf_name }}
          
          - interface {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].id_po }}{{ vlan_po }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_po }}
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].ip_po }}
          - no shutdown
            
          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}

          - interface Port-Channel12
          - switchport trunk allowed vlan add {{ vlan_id }}
          
          - route-map MPLS-RESPALDO-{{ vrf_name }} permit 10
          - set as-path prepend {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].as_path_prepend }}
          
          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].metric }}
          
          - router ospf {{ ospf_process_id }} vrf {{ vrf_name }}
          - router-id {{ second_ip }}
          - redistribute bgp route-map {{ vrf_name }}-TO-OSPF
          - network {{ segmento }} area {{ area }}
          
          - interface vlan {{ vlan_id }}
          - description INTER-RED-TDS-{{ vrf_name }}
          - vrf {{ vrf_name }}
          - ip address {{ second_ip }}/29
          - no shutdown
          
          - router bgp {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].router_id }} 
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].neighbor_ip }} remote-as 27651
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].router_id }} send-community extended
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].router_id }} maximum-routes 10000
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].neighbor_ip }} route-map MPLS-RESPALDO-{{ vrf_name }} out
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in
      when: 
        - site == 'CDLV' 
        - inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'
        - "'not found' in vlan_check.stdout[0]"
        - vrf_check.stdout[0] == ''
        - prefix_check.stdout[0] == ''
        - routemap_check.stdout[0] == ''    
        - routemap_check_resp.stdout[0] == ''
        - po_check_cdlv_b.stdout[0] == '' 
      changed_when: true
     
          
    - name: Configurar MPLS OSPF SVI ROUTE-MAP en AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }}
          
          - vlan {{ vlan_id }}
          - name INTER-RED-TDS-{{ vrf_name }}
          
          - interface {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ vlan_po }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_po }}
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].ip_po }}
          - no shutdown
          
          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}
          
          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].metric }}

          - interface Port-Channel12
          - switchport trunk allowed vlan add {{ vlan_id }}
          
          - router ospf {{ ospf_process_id }} vrf {{ vrf_name }}
          - router-id {{ first_ip }}
          - redistribute bgp route-map {{ vrf_name }}-TO-OSPF
          - network {{ segmento }} area {{ area }}
          
          - interface vlan {{ vlan_id }}
          - description INTER-RED-TDS-{{ vrf_name }}
          - vrf {{ vrf_name }}
          - ip address {{ first_ip }}/29
          - no shutdown
          
          - router bgp {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].router_id }} 
          - neighbor {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].neighbor_ip }} remote-as 27651
          - neighbor {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].neighbor_ip }} send-community extended
          - neighbor {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].neighbor_ip }} maximum-routes 10000
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in    
      when: 
        - site == 'AMU' 
        - inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'
        - "'not found' in vlan_check.stdout[0]"
        - vrf_check.stdout[0] == ''
        - prefix_check.stdout[0] == ''
        - routemap_check.stdout[0] == ''    
        - routemap_check_resp.stdout[0] == ''
        - po_check_amu_a.stdout[0] == ''       
      changed_when: true
      
  
    - name: Configurar MPLS OSPF SVI ROUTE-MAP en AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          
          - vlan {{ vlan_id }}
          - name INTER-RED-TDS-{{ vrf_name }}
          
          - interface {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ vlan_po }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_po }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].ip_po }}
          
          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}
          
          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].metric }}
          
          - route-map MPLS-RESPALDO-{{ vrf_name }} permit 10
          - set as-path prepend {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].as_path_prepend }}

          - interface Port-Channel12
          - switchport trunk allowed vlan add {{ vlan_id }}
          
          - router ospf {{ ospf_process_id }} vrf {{ vrf_name }}
          - router-id {{ second_ip }}
          - redistribute bgp route-map {{ vrf_name }}-TO-OSPF
          - network {{ segmento }} area {{ area }}
          
          - interface vlan {{ vlan_id }}
          - description INTER-RED-TDS-{{ vrf_name }}
          - vrf {{ vrf_name }}
          - ip address {{ second_ip }}/29
          - no shutdown
          
          - router bgp {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].router_id }} 
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} remote-as 27651
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} send-community extended
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} maximum-routes 10000
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} route-map MPLS-RESPALDO-{{ vrf_name }} out
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in
      when: 
        - site == 'AMU' 
        - inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'
        - "'not found' in vlan_check.stdout[0]"
        - vrf_check.stdout[0] == ''
        - prefix_check.stdout[0] == ''
        - routemap_check.stdout[0] == ''    
        - routemap_check_resp.stdout[0] == ''
        - po_check_amu_b.stdout[0] == ''   
      changed_when: true
      


    
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
