---
- name: rollback de configuracion CREAR_MPLS_ESC
  hosts: all
  gather_facts: no
  vars:
    vrf_name: ""
    site: ""
  tasks:
    - name: Eliminar la definición de la VRF
      arista.eos.eos_config:
        lines:
        - enable
        - configure terminal
        - router bgp 65121
        - no vrf LG
