- name: Configurar OSPF en el dispositivo Arista CDLV
  hosts: all
  gather_facts: no

  vars:
    vrf_name: ""
    router_id: ""
    route_map: ""
    network: ""
    area: "0.0.0.0"

  tasks:
    - name: Obtener la configuración OSPF actual
      arista.eos.eos_command:
        commands:
          - show running-config section router ospf
      register: ospf_config

    - name: Analizar IDs de OSPF actuales
      set_fact:
        ospf_ids: "{{ ospf_config.stdout[0] | regex_findall('router ospf (\\d+)') | map('int') | list }}"

    - name: Determinar el siguiente ID de OSPF disponible
      set_fact:
        ospf_process_id: "{{ (ospf_ids | sort | last | default(0)) + 1 }}"

    - name: Debug del próximo ID de OSPF disponible
      debug:
        msg: "El próximo ID de OSPF disponible es: {{ ospf_process_id }}"

    - name: Verificar existencia de la route-map
      arista.eos.eos_command:
        commands:
          - show running-config section route-map
      register: route_map_config

    - name: Validar si la route-map existe
      set_fact:
        route_map_exists: "{{ route_map in route_map_config.stdout[0] }}"

    - name: Debug Validar si la route-map existe
      debug:
        msg: "La route-map '{{ route_map }}' existe: {{ route_map_exists }}"

    - name: Verificar existencia de la VRF
      arista.eos.eos_command:
        commands:
          - show vrf
      register: vrf_config

    - name: Validar si la VRF existe
      set_fact:
        vrf_exists: "{{ vrf_name in vrf_config.stdout[0] }}"

    - name: Debug Validar si la VRF existe
      debug:
        msg: "La VRF '{{ vrf_name }}' existe: {{ vrf_exists }}"

    - name: Verificar existencia de OSPF para la VRF
      set_fact:
        ospf_vrf_exists: "{{ ('router ospf ' ~ ospf_process_id ~ ' vrf ' ~ vrf_name) in ospf_config.stdout[0] }}"

    - name: Debug Validar si OSPF para la VRF existe
      debug:
        msg: "El OSPF para la VRF '{{ vrf_name }}' ya existe: {{ ospf_vrf_exists }}"

    - name: Configurar OSPF solo si la route-map, la VRF existen y el OSPF para la VRF no existe
      arista.eos.eos_command:
        commands:
          - configure terminal
          - router ospf {{ ospf_process_id }} vrf {{ vrf_name }}
          - router-id {{ router_id }}
          - redistribute bgp route-map {{ route_map }}
          - network {{ network }} area {{ area }}
      register: ospf_config_result
      when: route_map_exists and vrf_exists and not ospf_vrf_exists
      changed_when: true

    - name: Debug Configuración de OSPF
      debug:
        msg: "Resultado de la configuración de OSPF: {{ ospf_config_result }}"
      when: route_map_exists and vrf_exists and not ospf_vrf_exists

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
      when: route_map_exists and vrf_exists and not ospf_vrf_exists

    - name: Debug Guardar cambios
      debug:
        msg: "Cambios guardados en la configuración."
      when: route_map_exists and vrf_exists and not ospf_vrf_exists


