---
- name: Configurar BGP en el dispositivo Arista CDLV
  hosts: all
  gather_facts: no

  vars:
    bgp_asn: ""              
    vrf_name: ""               
    neighbor_ip: ""            
    router_id: "{{ neighbor_ip }}"             
    network: ""                
    filtro_in_bgp: ""         

  tasks:
    - name: Configurar BGP
      arista.eos.eos_command:
        commands:
          - enable
          - configure terminal
          - router bgp {{ bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ router_id }}
          - neighbor {{ neighbor_ip }} remote-as 27651
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ neighbor_ip }} prefix-list {{ filtro_in_bgp }} in
      register: bgp_config_result
      changed_when: true
      failed_when: false

    - name: Debug Configurar BGP
      debug:
        msg: "Resultado de la configuración de BGP: {{ bgp_config_result }}"

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
