---
- name: Anunciar segmento publico BGP en switch Arista
  hosts: all
  gather_facts: no

  # Variables
  vars:
    bgp_id: ""
    vrf_nam: ""
    prefix_mask: ""

  # Tareas
  tasks:
    - name: Verificar existencia de AS BGP
      arista.eos.eos_command:
        commands:
          - show bgp instance | in {{ bgp_id }}
      register: bgp_check

    - name: Mostrar resultado del comando show bgp instance
      debug:
        msg: "{{ bgp_check.stdout }}"

    - name: Verificar existencia de la VRF
      arista.eos.eos_command:
        commands:
          - show vrf | in {{ vrf_nam }}
      register: vrf_check

    - name: Mostrar resultado del comando show vrf 
      debug:
        msg: "{{ vrf_check.stdout }}"
        
    - name: Anunciar segmento BGP para la VRF
      arista.eos.eos_command:
        commands:
          - configure terminal
          - router bgp {{ bgp_id }}
          - vrf {{ vrf_nam }}
          - network {{ prefix_mask }}
      when: vrf_nam in vrf_check.stdout[0]

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory

    - name: Verificar segmento publico BGP
      arista.eos.eos_command:
        commands:
          - show bgp configuration active 
      register: bgp_check_new

    - name: Mostrar resultado del comando show bgp id después de asignar segmento publico
      debug:
        msg: "{{ bgp_check_new.stdout }}"
