- name: crear mpls, vrf, ospf, bgp
  hosts: all
  gather_facts: no

  vars:
    site: ""
    vlan_po: ""
    vlan_id: ""
    segmento: ""
    vrf_name: ""
    equipos_config:
      AMU-P5-E4-UR29-BLEAF-A:
        bgp_asn: "65021"
        neighbor_ip: "169.254.196.9"
        router_id: "169.254.196.9"
        id_po: "Port-Channel5."
        ip_po: "169.254.196.10/30"
      AMU-P5-E3-UR29-BLEAF-B:
        bgp_asn: "65021"
        neighbor_ip: "169.254.196.13"
        router_id: "169.254.196.13"
        id_po: "Port-Channel6."
        ip_po: "169.254.196.14/30"
      CDLV-212-G31-UR29-BLEAF-A:
        bgp_asn: "65121"
        neighbor_ip: "169.254.196.17"
        router_id: "169.254.196.17"
        id_po: "Port-Channel5."
        ip_po: "169.254.196.18/30"
      CDLV-212-G32-UR29-BLEAF-B:
        bgp_asn: "65121"
        neighbor_ip: "169.254.196.21"
        router_id: "169.254.196.21"
        id_po: "Port-Channel6."
        ip_po: "169.254.196.22/30"

  tasks:
  
    - name: Verificar existencia de la VRF
      arista.eos.eos_command:
        commands:
          - show vrf | in {{ vrf_name }}
      register: vrf_check

      
    - name: Verificar existencia del prefix-list
      arista.eos.eos_command:
        commands:
          - show running-config section ip prefix-list
      register: prefix_list_config
          - name: Validar si la prefix-list existe
      set_fact:
        prefix_list_exists: "{{ ('ip prefix-list ' ~ filtro_in_bgp) in prefix_list_config.stdout[0] }}"
        

    - name: Verificar vecinos BGP existentes
      arista.eos.eos_command:
        commands:
          - show running-config section bgp | sec vrf {{ vrf_name }}
      register: bgp_running_config
   - name: Validar si el vecino BGP ya existe
      set_fact:
        neighbor_exists: "{{ neighbor_ip in bgp_running_config.stdout[0] }}"
      

    - name: Verificar existencia del port-channel en equipo CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
      register: po_check_cdlv_a
      when: site == 'CDLV' and inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'

    - name: Verificar existencia del port-channel en equipo CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
      register: po_check_cdlv_b
      when: site == 'CDLV' and inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'

    - name: Verificar existencia del port-channel en equipo AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
      register: po_check_amu_a
      when: site == 'AMU' and inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'

    - name: Verificar existencia del port-channel en equipo AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
      register: po_check_amu_b
      when: site == 'AMU' and inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'

  
    - name: Configurar la interfaz para equipo CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          - interface {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].ip_po }}
          - router bgp {{ bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ router_id }}
          - neighbor {{ neighbor_ip }} remote-as 27651
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ neighbor_ip }} prefix-list {{ filtro_in_bgp }} in
      when: site == 'CDLV' and "'' in vrf_check.stdout[0]" and "'' in po_check_cdlv_a[0]" and inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'


    - name: Configurar la interfaz para equipo CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          - interface {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].ip_po }}
      when: site == 'CDLV' and "'' in vrf_check.stdout[0]" and "'' in po_check_cdlv_b[0]" and inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'


    - name: Configurar la interfaz para equipo AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          - interface {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].ip_po }}
      when: site == 'CDLV' and "'' in vrf_check.stdout[0]" and "'' in po_check_amu_a[0]" and inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'

    - name: Configurar la interfaz para equipo AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          - interface {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].ip_po }}
      when: site == 'CDLV' and "'' in vrf_check.stdout[0]" and "'' in po_check_amu_b[0]" and inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
