---
- name: "[PLAY-1] EJECUCION DE COMMAND -> RAW MODULE"
  hosts: localhost
  gather_facts: true
  become: no

  vars:
    read_file_path_base: "/etc"
    read_file_name: "hosts"
    read_file_path_full: "{{ read_file_path_base }}/{{ read_file_name }}"
    search_string: "127.0.0.1"
    raw_command_1: >
      cat {{ read_file_path_full }} | grep {{ search_string }} | wc -l

  pre_tasks:

  - ansible.builtin.assert:
      that:
        - read_file_path_base is defined
        - read_file_path_base != ""
        - read_file_name is defined
        - read_file_name != ""
        - read_file_path_full is defined
        - read_file_path_full != ""
        - search_string is defined
        - search_string != ""
        - raw_command_1 is defined and raw_command_1 != ""
      success_msg: "'VALIDATION [VARS] -> SUCCESS"

  tasks:

  - ansible.builtin.debug:
      msg: "INFO: FILE TO READ -> '{{ read_file_path_full }}'"

  - name: "INFO: TEST"
    raw: "{{ raw_command_1 }}"
    register: reg_cmdraw_1

  - ansible.builtin.assert:
      that:
        - reg_cmdraw_1.stdout is defined
        - reg_cmdraw_1.stdout != ""
        - reg_cmdraw_1.stdout | trim | int == 1
      fail_msg: "ERROR: STRING NOT FOUND IN FILE."


