- name: Configurar la interfaz Port-Channel5.534 en el equipo AMU-P5-E4-UR29-BLEAF-A
  hosts: AMU-P5-E4-UR29-BLEAF-A
  gather_facts: no

  vars:
    site: ""
    vlan_id: 534
    vrf_name: ""
    equipo_config:
      AMU-P5-E3-UR29-BLEAF-B:
        ip_address: 
        description: 
        as_path_prepend: "65021"
      CDLV-212-G32-UR29-BLEAF-B:
        bgp_as_number: "65121"
        neighbor_ip: "169.254.196.21"
        as_path_prepend: "65121"
AMU-P5-E4-UR29-BLEAF-A

AMU-P5-E3-UR29-BLEAF-B

      

interface_name: "Port-Channel5.534"
  tasks:
    - name: Configurar la interfaz {{ interface_name }}
      arista.eos.eos_config:
        lines:
          - description {{ description }}
          - encapsulation dot1q vlan {{ vlan_id }}
          - vrf {{ vrf_name }}
          - ip address {{ ip_address }}
        parents: interface {{ interface_name }}

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory




          
  vars:
    vrf_name: ""
    equipo: ""
    route_map_name: "MPLS-RESPALDO-{{ vrf_name }}"
    equipos_config:
      AMU-P5-E3-UR29-BLEAF-B:
        bgp_as_number: "65021"
        neighbor_ip: "169.254.196.13"
        as_path_prepend: "65021"
      CDLV-212-G32-UR29-BLEAF-B:
        bgp_as_number: "65121"
        neighbor_ip: "169.254.196.21"
        as_path_prepend: "65121"
    

  tasks:
    - name: Depurar valor de equipos
      debug:
        msg: "Valores de equipos: '{{ equipo }}'"

    - name: Asignar valores según equipos seleccionados
      set_fact:
        bgp_asn: "{{ equipos_config[item].bgp_as_number }}"
        neighbor_ip: "{{ equipos_config[item].neighbor_ip }}"
        as_path_prepend: "{{ equipos_config[item].as_path_prepend }}"
      with_items: "{{ equipo }}"
      when: item in equipos_config

    - name: Debug Asignar bgp_asn, neighbor_ip y as_path_prepend
      debug:
        msg: 
          - "ASN BGP asignado: {{ bgp_asn }}"
          - "IP del vecino BGP asignada: {{ neighbor_ip }}"
          - "AS Path Prepend asignado: {{ as_path_prepend }}"

    - name: Verificar existencia del route-map
      arista.eos.eos_command:
        commands:
          - show running-config section route-map
      register: route_map_config

    - name: Debug Verificar existencia del route-map
      debug:
        msg: "{{ route_map_config.stdout }}"

    - name: Verificar si el route-map ya está configurado
      set_fact:
        route_map_exists: "{{ ('route-map ' ~ route_map_name) in route_map_config.stdout[0] }}"

    - name: Verificar existencia de la VRF
      arista.eos.eos_command:
        commands:
          - show vrf
      register: vrf_config

    - name: Debug Verificar existencia de la VRF
      debug:
        msg: "{{ vrf_config.stdout }}"

    - name: Verificar si la VRF existe
      set_fact:
        vrf_exists: "{{ vrf_name in vrf_config.stdout[0] }}"

    - name: Configurar route-map solo si no existe y si la VRF existe
      arista.eos.eos_command:
        commands:
          - configure terminal
          - route-map {{ route_map_name }} permit 10
          - set as-path prepend {{ as_path_prepend }}
      register: route_map_config_result
      when: not route_map_exists and vrf_exists
      changed_when: true
      failed_when: false

    - name: Debug Configurar route-map
      debug:
        msg: "Resultado de la configuración del route-map: {{ route_map_config_result }}"
      when: not route_map_exists and vrf_exists

    - name: Verificar si el route-map fue creado
      set_fact:
        route_map_created: "{{ not route_map_exists and vrf_exists }}"

    - name: Configurar BGP solo si la VRF existe y el route-map fue creado
      arista.eos.eos_command:
        commands:
          - configure terminal
          - router bgp {{ bgp_asn }}
          - vrf {{ vrf_name }}
          - neighbor {{ neighbor_ip }} route-map {{ route_map_name }} out
      register: bgp_config
      when: route_map_created and vrf_exists
      changed_when: true
      failed_when: false

    - name: Debug Configurar BGP
      debug:
        msg: "Resultado de la configuración de BGP: {{ bgp_config }}"
      when: route_map_created and vrf_exists

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory

