---
- name: rollback de configuracion CREAR_MPLS_ESC
  hosts: all
  gather_facts: no
  
  vars:
    vrf_name: ""
    site: ""
    equipos_config:
      AMU-P5-E4-UR29-BLEAF-A:
        bgp_asn: "65021"
        id_po: "Port-Channel5."
      AMU-P5-E3-UR29-BLEAF-B:
        bgp_asn: "65021"
        id_po: "Port-Channel6."
      CDLV-212-G31-UR29-BLEAF-A:
        bgp_asn: "65121"
        id_po: "Port-Channel5."
      CDLV-212-G32-UR29-BLEAF-B:
        bgp_asn: "65121"
        id_po: "Port-Channel6."
  
  tasks:
    - name: Verificar existencia de la VRF
      arista.eos.eos_command:
        commands:
          - show vrf | include {{ vrf_name }}
      register: vrf_check

    - name: Debug VRF check
      debug:
        var: vrf_check.stdout

    - name: Ejecutar el comando para obtener la información de la VRF
      arista.eos.eos_command:
        commands:
        - show ip route vrf {{ vrf_name }} connected
      register: vrf_output

    - name: Extraer la VLAN ID en CDLV
      set_fact:
       vlan_id: "{{ (vrf_output.stdout[0] | regex_search('Vlan(\\d+)', '\\1')) | first }}"
      when: 
        - site == 'CDLV' 
        - "(inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A' or inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B')"

    - name: Extraer la VLAN ID en AMU
      set_fact:
       vlan_id: "{{ (vrf_output.stdout[0] | regex_search('Vlan(\\d+)', '\\1')) | first }}"
      when: 
        - site == 'AMU' 
        - "(inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A' or inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B')"

    - name: Extraer el Port-Channel
      set_fact:
       port_channel: "{{ (vrf_output.stdout[0] | regex_search('Port-Channel\\d+\\.?(\\d+)?', '\\1')) | first }}"

    - name: Mostrar los valores extraídos
      debug:
        msg: 
           - "VLAN ID: {{ vlan_id }}"
           - "Port-Channel: {{ port_channel }}"

    - name: Ejecutar el comando para obtener la información de OSPF
      arista.eos.eos_command:
         commands:
          - show ip ospf vrf {{ vrf_name }} | i instance 
      register: ospf_output

    - name: Extraer la instancia de OSPF
      set_fact:
       ospf_instance_id: "{{ ospf_output.stdout | regex_search('OSPF instance (\\d+)', '\\1') | first }}"

    - name: Mostrar la instancia de OSPF extraída
      debug:
        msg: "Instancia de OSPF: {{ ospf_instance_id }}"


    - name: Eliminar configuraciones relacionadas para CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - interface Port-Channel 12
          - switchport trunk allowed vlan remove {{ vlan_id }}
          - router bgp 65121
          - no vrf {{ vrf_name }}
          - no ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - no route-map {{ vrf_name }}-TO-OSPF
          - no router ospf {{ ospf_instance_id }} vrf {{ vrf_name }}
          - no interface vlan {{ vlan_id }}
          - no interface {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].id_po }}{{ port_channel }}
          - no vlan {{ vlan_id }}
          - no vrf instance {{ vrf_name }}
      when: 
          - vrf_check.stdout[0] != ''
          - site == 'CDLV' 
          - inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'
      changed_when: true

    - name: Eliminar configuraciones relacionadas para CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - interface Port-Channel 12
          - switchport trunk allowed vlan remove {{ vlan_id }}
          - router bgp 65121
          - no vrf {{ vrf_name }}
          - no ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - no route-map {{ vrf_name }}-TO-OSPF
          - no route-map MPLS-RESPALDO-{{ vrf_name }} 
          - no router ospf {{ ospf_instance_id }} vrf {{ vrf_name }}
          - no interface vlan {{ vlan_id }}
          - no interface {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].id_po }}{{ port_channel }}
          - no vlan {{ vlan_id }}
          - no vrf instance {{ vrf_name }}
      when: 
          - vrf_check.stdout[0] != ''
          - site == 'CDLV' 
          - inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'
      changed_when: true

    - name: Eliminar toda la configuración para AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - interface Port-Channel 12
          - switchport trunk allowed vlan remove {{ vlan_id }}
          - router bgp 65021
          - no vrf {{ vrf_name }}
          - no ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - no route-map {{ vrf_name }}-TO-OSPF
          - no router ospf {{ ospf_instance_id }} vrf {{ vrf_name }}
          - no interface vlan {{ vlan_id }}
          - no interface {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ port_channel }}
          - no vlan {{ vlan_id }}
          - no vrf instance {{ vrf_name }} 
      when: 
       - vrf_check.stdout[0] != ''
       - site == 'AMU' 
       - inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'
      changed_when: true

    - name: Eliminar toda la configuración para AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - interface Port-Channel 12
          - switchport trunk allowed vlan remove {{ vlan_id }}
          - router bgp 65021
          - no vrf {{ vrf_name }}
          - no ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - no route-map {{ vrf_name }}-TO-OSPF
          - no route-map MPLS-RESPALDO-{{ vrf_name }} 
          - no router ospf {{ ospf_instance_id }} vrf {{ vrf_name }}
          - no interface vlan {{ vlan_id }}   
          - no interface {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ port_channel }}
          - no vlan {{ vlan_id }}
          - no vrf instance {{ vrf_name }}
      when: 
       - vrf_check.stdout[0] != ''
       - site == 'AMU' 
       - inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'
      changed_when: true
    
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory

    - name: Debug guardado de cambios
      debug:
        msg: "Cambios guardados en el dispositivo."

