---
- name: Crear route-map MPLS_RESPALDO_AMU
  hosts: all
  gather_facts: no

  vars:
    route_map_name: ""
    bgp_as_number: "65021"
    vrf_name: ""
    neighbor_ip: ""
    as_path_prepend: "{{ bgp_as_number }}"  # Asegura que as_path_prepend sea igual a bgp_as_number

  tasks:
    - name: Verificar si el route-map ya existe
      arista.eos.eos_command:
        commands:
          - show route-map {{ route_map_name }}
      register: route_map_check
      failed_when: false

    - name: Configurar route-map solo si no existe
      arista.eos.eos_command:
        commands:
          - configure terminal
          - route-map {{ route_map_name }} permit 10
          - set as-path prepend {{ as_path_prepend }}
      register: route_map_config
      changed_when: "'Invalid input' not in route_map_config.stdout"
      when: route_map_check.stdout[0] is not defined or 'Invalid input' in route_map_check.stdout[0]

    - name: Debug Configurar route-map
      debug:
        msg: "Resultado de la configuración del route-map: {{ route_map_config }}"
      when: route_map_check.stdout[0] is not defined or 'Invalid input' in route_map_check.stdout[0]

    - name: Configurar BGP
      arista.eos.eos_command:
        commands:
          - configure terminal
          - router bgp {{ bgp_as_number }}
          - vrf {{ vrf_name }}
          - neighbor {{ neighbor_ip }} route-map {{ route_map_name }} out
      register: bgp_config
      changed_when: "'Invalid input' not in bgp_config.stdout"

    - name: Debug Configurar BGP
      debug:
        msg: "Resultado de la configuración de BGP: {{ bgp_config }}"

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
      register: save_config

    - name: Debug Guardar cambios
      debug:
        msg: "Resultado de guardar cambios: {{ save_config }}"
