---
- name: Comprobar y crear route-map en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_route_map: ""
    nom_prefix: ""
    metric: ""

 
  # Tareas
  tasks:
    - name: Verificar existencia del route-map
      arista.eos.eos_command:
        commands:
          - show running-config | include route-map {{ nom_route_map }}
      register: routemap_check
      ignore_errors: yes
      
    # Salida por pantalla
    - name: Mostrar resultado del Verificador existencia del route-map
      debug:
        msg: "{{ routemap_check.stdout }}"

    - name: Crear route-map si no existe
      arista.eos.eos_config:
        lines:
          - route-map {{ nom_route_map }} permit 10
          - match ip address prefix-list {{ nom_prefix }}
          - set metric {{ metric }}
      when: "'' in routemap_check.stdout[0]"
        
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
        
