---
- name: Comprobar y crear route-map en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_route_map: ""
    nom_prefix: ""
    metric: ""
  # Tareas
  tasks:
    - name: Obtener configuraci贸n actual del Route-Map
      arista.eos.eos_command:
        commands:
          - "show running-config section route-map"
      register: route_map_config

    - name: Debug de la configuraci贸n actual del Route-Map
      debug:
        msg: "Configuraci贸n actual del Route-Map: {{ route_map_config.stdout }}"

    - name: Validar existencia del Route-Map
      set_fact:
        route_map_exists: "{{ 'route-map ' ~ nom_route_map in route_map_config.stdout[0] }}"

    - name: Debug del estado de existencia del Route-Map
      debug:
        msg: "El Route-Map {{ nom_route_map }} existe: {{ route_map_exists }}"

    - name: Configurar Route-Map si no existe
      arista.eos.eos_command:
        commands:
          - "configure terminal"
          - "route-map {{ nom_route_map }} permit 10"
          - "match ip address prefix-list {{ nom_prefix }}"
          - "set metric {{ metric }}"
      when: not route_map_exists



    - name: Guardar configuraci贸n
      arista.eos.eos_command:
        commands:
          - "write memory"
      when: route_map_configured is defined and route_map_configured.changed
