---
- name: Eliminar configuraci贸n de MORADO basada en show run para Arista
  hosts: switches
  gather_facts: no
  tasks:
    - name: Obtener la configuraci贸n de la secci贸n MORADO
      eos_command:
        commands:
          - show running-config section morado
      register: morado_config

    - name: Extraer VLAN ID
      set_fact:
        vlan_id: "{{ morado_config.stdout[0] | regex_search('vlan (\\d+)', '\\1') }}"

    - name: Extraer VRF name
      set_fact:
        vrf_name: "{{ morado_config.stdout[0] | regex_search('vrf instance (\\S+)', '\\1') }}"

    - name: Extraer Port-Channel
      set_fact:
        port_channel: "{{ morado_config.stdout[0] | regex_search('interface (Port-Channel\\d+\\.\\d+)', '\\1') }}"

    - name: Extraer VLAN interface
      set_fact:
        vlan_interface: "{{ morado_config.stdout[0] | regex_search('interface Vlan(\\d+)', 'Vlan\\1') }}"

    - name: Extraer prefix-list name
      set_fact:
        prefix_list: "{{ morado_config.stdout[0] | regex_search('ip prefix-list (\\S+)', '\\1') }}"

    - name: Extraer route-map name
      set_fact:
        route_map: "{{ morado_config.stdout[0] | regex_search('route-map (\\S+)', '\\1') }}"

    - name: Eliminar toda la configuraci贸n de MORADO
      eos_config:
        lines:
          - "no vlan {{ vlan_id }}"
          - "no vrf definition {{ vrf_name }}"
          - "interface {{ port_channel }}"
          - "  no vrf forwarding {{ vrf_name }}"
          - "  no description"
          - "  no interface {{ port_channel }}"
          - "interface {{ vlan_interface }}"
          - "  no vrf forwarding {{ vrf_name }}"
          - "  no description"
          - "  no interface {{ vlan_interface }}"
          - "no ip routing vrf {{ vrf_name }}"
          - "no ip prefix-list {{ prefix_list }} seq 10 permit 10.200.0.0/24"
          - "no route-map {{ route_map }} permit 10"
          - "router bgp 65121"
          - "  no vrf {{ vrf_name }}"
          - "  no neighbor 169.254.196.17 remote-as 27651"
          - "  no network 192.168.100.0/24"
          - "  no address-family ipv4"
          - "router ospf 3 vrf {{ vrf_name }}"
          - "  no router-id 10.20.20.1"
          - "  no redistribute bgp route-map {{ route_map }}"
          - "  no network 10.20.20.0/29 area 0.0.0.0"
          - "  no max-lsa 12000"
        save_when: modified

