---
- name: Rollback prefix-list o ID
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    site: ""
    eliminar: ""
    nom_prefix: ""
    id_prefix: ""
    
  # Tareas
  tasks:

    - name: Verificar existencia del prefix-list
      arista.eos.eos_command:
        commands:
          - show run | i ip prefix-list {{ nom_prefix }}
      register: prefix_check

    - name: Debug prefix check
      debug:
        var: prefix_check.stdout 

    - name: eliminar id de prefix-list
      arista.eos.eos_command:
        commands:
          - configure terminal
          - ip prefix-list {{ nom_prefix }}
          - no seq {{ id_prefix }} 
  when: 
        - site == 'CDLV' 
        - eliminar == 'ID' 
        - "(inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A' or inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B')"
        - prefix_check.stdout[0] != ''
  changed_when: true

      - name: eliminar id de prefix-list
      arista.eos.eos_command:
        commands:
          - configure terminal
          - ip prefix-list {{ nom_prefix }}
          - no seq {{ id_prefix }} 
  when: 
        - site == 'AMU' 
        - eliminar == 'ID' 
        - "(inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A' or inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B')"
        - prefix_check.stdout[0] != ''
  changed_when: true






  - name: eliminar PREFIX-LIST de prefix-list
      arista.eos.eos_command:
        commands:
          - configure terminal
          - no ip prefix-list {{ nom_prefix }}   
  when: 
        - site == 'AMU' 
        - eliminar == 'PREFIX-LIST' 
        - "(inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A' or inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B')"
        - prefix_check.stdout[0] != ''
  changed_when: true

      - name: eliminar id de prefix-list
      arista.eos.eos_command:
        commands:
          - configure terminal
          - no ip prefix-list {{ nom_prefix }}    
  when: 
        - site == 'AMU' 
        - eliminar == 'PREFIX-LIST' 
        - "(inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A' or inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B')"
        - prefix_check.stdout[0] != ''
  changed_when: true

   - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
