---
- name: rollback de configuracion CREAR_MPLS_ESC
  hosts: all
  gather_facts: no
  
  vars:
    vrf_name: ""
    site: ""
    equipos_config:
      AMU-P5-E4-UR29-BLEAF-A:
        bgp_asn: "65021"
        id_po: "Port-Channel5."
      AMU-P5-E3-UR29-BLEAF-B:
        bgp_asn: "65021"
        id_po: "Port-Channel6."
      CDLV-212-G31-UR29-BLEAF-A:
        bgp_asn: "65121"
        id_po: "Port-Channel5."
      CDLV-212-G32-UR29-BLEAF-B:
        bgp_asn: "65121"
        id_po: "Port-Channel6."
  
  tasks:

    - name: Eliminar configuraciones relacionadas para CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_config:
         lines:
          - configure terminal
          - router bgp 65121
          - no vrf ARCEUS
      when: 
          - site == 'CDLV' 
          - inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'
      changed_when: true


    
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory

    - name: Debug guardado de cambios
      debug:
        msg: "Cambios guardados en el dispositivo."

