- name: crear mpls, vrf, ospf, bgp, svi, route-map
  hosts: all
  gather_facts: no

  vars:
    site: ""
    vlan_po: ""
    vlan_id: ""
    segmento: ""
    vrf_name: ""
    network: ""
    prefix_in: ""
    area: "0.0.0.0"
    equipos_config:
      AMU-P5-E4-UR29-BLEAF-A:
        bgp_asn: "65021"
        neighbor_ip: "169.254.196.9"
        router_id: "169.254.196.10"
        id_po: "Port-Channel5."
        ip_po: "169.254.196.10/30"
        metric: "30000"
      AMU-P5-E3-UR29-BLEAF-B:
        bgp_asn: "65021"
        neighbor_ip: "169.254.196.13"
        router_id: "169.254.196.14"
        id_po: "Port-Channel6."
        ip_po: "169.254.196.14/30"
        as_path_prepend: "65021"
        metric: "40000"
      CDLV-212-G31-UR29-BLEAF-A:
        bgp_asn: "65121"
        neighbor_ip: "169.254.196.17"
        router_id: "169.254.196.18"
        id_po: "Port-Channel5."
        ip_po: "169.254.196.18/30"
        metric: "10000"
      CDLV-212-G32-UR29-BLEAF-B:
        bgp_asn: "65121"
        neighbor_ip: "169.254.196.21"
        router_id: "169.254.196.22"
        id_po: "Port-Channel6."
        ip_po: "169.254.196.22/30"
        as_path_prepend: "65121"
        metric: "20000"

  tasks:

    - name: Verificar existencia de la VRF
      arista.eos.eos_command:
        commands:
          - show vrf | in {{ vrf_name }}
      register: vrf_check
      
    - name: Debug VRF check
      debug:
        var: vrf_check.stdout

    - name: Verificar existencia del prefix-list
      arista.eos.eos_command:
        commands:
          - show running-config section ip prefix-list | i {{ vrf_name }}-ESC-TO-BGP-IN
      register: prefix_check

    - name: Debug prefix-list check
      debug:
        var: prefix_check.stdout
    
    - name: Verificar existencia del route-map
      arista.eos.eos_command:
        commands:
          - show running-config section route-map | i {{ vrf_name }}-TO-OSPF
      register: routemap_check

    - name: Debug route-map check
      debug:
        var: routemap_check.stdout

    - name: Verificar existencia del route-map de respaldo
      arista.eos.eos_command:
        commands:
          - show running-config section route-map | i MPLS-RESPALDO-{{ vrf_name }}
      register: routemap_check_resp
      
    - name: Debug route-map respaldo check
      debug:
        var: routemap_check_resp.stdout
        
    - name: Verificar existencia del port-channel en equipo CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
      register: po_check_cdlv_a
      when: site == 'CDLV' and inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'

    - name: Debug port-channel check CDLV-A
      debug:
        var: po_check_cdlv_a.stdout
      when: site == 'CDLV' and inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'

  
    - name: Verificar existencia del port-channel en equipo CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
      register: po_check_cdlv_b
      when: site == 'CDLV' and inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'

    - name: Debug port-channel check CDLV-B
      debug:
        var: po_check_cdlv_b.stdout
      when: site == 'CDLV' and inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'

  
    - name: Verificar existencia del port-channel en equipo AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
      register: po_check_amu_a
      when: site == 'AMU' and inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'

    - name: Debug port-channel check AMU-A
      debug:
        var: po_check_amu_a.stdout
      when: site == 'AMU' and inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'


    - name: Verificar existencia del port-channel en equipo AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
      register: po_check_amu_b
      when: site == 'AMU' and inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'

    - name: Debug port-channel check AMU-B
      debug:
        var: po_check_amu_b.stdout
      when: site == 'AMU' and inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'


    - name: Obtener la configuración OSPF actual
      arista.eos.eos_command:
        commands:
          - show running-config section router ospf
      register: ospf_config

    - name: Debug OSPF config
      debug:
        var: ospf_config.stdout
    
    - name: Analizar IDs de OSPF actuales
      set_fact:
        ospf_ids: "{{ ospf_config.stdout[0] | regex_findall('router ospf (\\d+)') | map('int') | list }}"

    - name: Determinar el siguiente ID de OSPF disponible
      set_fact:
        ospf_process_id: "{{ (ospf_ids | sort | last | default(0)) + 1 }}"

    - name: Debug del próximo ID de OSPF disponible
      debug:
        msg: "El próximo ID de OSPF disponible es: {{ ospf_process_id }}"


    - name: Verificar existencia de la VLAN
      arista.eos.eos_command:
        commands:
          - show vlan id {{ vlan_id }}
      register: vlan_check

      
    - name: Debug VLAN check
      debug:
        var: vlan_check.stdout

    - name: Extraer la dirección base y la máscara del segmento
      set_fact:
        ip_base: "{{ segmento.split('/')[0].split('.')[:-1] | join('.') }}"
        last_octet: "{{ segmento.split('/')[0].split('.')[-1] }}"
        subnet_mask: "{{ segmento.split('/')[1] }}"

    - name: Debug IP base y máscara
      debug:
        msg:
        - "IP Base: {{ ip_base }}"
        - "Último octeto: {{ last_octet }}"
        - "Máscara de subred: {{ subnet_mask }}"
      

    - name: Calcular la primera IP disponible en el segmento
      set_fact:
        first_ip: "{{ ip_base }}.{{ last_octet | int + 1 }}"

    - name: Calcular la segunda IP disponible en el segmento
      set_fact:
        second_ip: "{{ ip_base }}.{{ last_octet | int + 2 }}"
        
    - name: Mostrar las IPs calculadas
      debug:
        msg:
          - "Primera IP: {{ first_ip }}"
          - "Segunda IP: {{ second_ip }}"

    - name: Configurar MPLS OSPF SVI ROUTE-MAP en CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          
          - vlan {{ vlan_id }}
          - name INTER-RED-TDS-{{ vrf_name }}
          
          - interface {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].ip_po }}
          - no shutdown
          
          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}
          
          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].metric }}
          
          - router ospf {{ ospf_process_id }} vrf {{ vrf_name }}
          - router-id {{ first_ip }}
          - redistribute bgp route-map {{ vrf_name }}-TO-OSPF
          - network {{ network }} area {{ area }}
          
          - interface vlan {{ vlan_id }}
          - description INTER-RED-TDS-{{ vrf_name }}
          - vrf {{ vrf_name }}
          - ip address {{ first_ip }}/29
          - no shutdown
          
          - router bgp {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].router_id }} 
          - neighbor {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].neighbor_ip }} remote-as 27651  
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in
      when: 
        - site == 'CDLV' 
        - inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'
        - "'not found' in vlan_check.stdout[0]"
        - vrf_check.stdout[0] == ''
        - prefix_check.stdout[0] == ''
        - routemap_check.stdout[0] == ''    
        - routemap_check_resp.stdout[0] == ''
        - po_check_cdlv_a.stdout[0] == ''       
      changed_when: true
  rescue:
    - name: Mostrar debug del porqué no se ejecutó la tarea
      debug:
        msg: >
          La tarea no se ejecutó porque:
          site = {{ site }},
          inventory_hostname = {{ inventory_hostname }},
          vlan_check.stdout = {{ vlan_check.stdout }},
          vrf_check.stdout = {{ vrf_check.stdout }},
          prefix_check.stdout = {{ prefix_check.stdout }},
          routemap_check.stdout = {{ routemap_check.stdout }},
          routemap_check_resp.stdout = {{ routemap_check_resp.stdout }},
          po_check_cdlv_a.stdout = {{ po_check_amu_b.stdout }}
          
    - name: Configurar MPLS OSPF SVI ROUTE-MAP en CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          - vlan {{ vlan_id }}
          - name INTER-RED-TDS-{{ vrf_name }}
          
          - interface {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].ip_po }}
          - no shutdown
            
          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}
          
          - route-map MPLS-RESPALDO-{{ vrf_name }} permit 10
          - set as-path prepend {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].as_path_prepend }}
          
          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].metric }}
          
          - router ospf {{ ospf_process_id }} vrf {{ vrf_name }}
          - router-id {{ second_ip }}
          - redistribute bgp route-map {{ vrf_name }}-TO-OSPF
          - network {{ network }} area {{ area }}
          
          - interface vlan {{ vlan_id }}
          - description INTER-RED-TDS-{{ vrf_name }}
          - vrf {{ vrf_name }}
          - ip address {{ second_ip }}/29
          - no shutdown
          
          - router bgp {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].router_id }} 
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].neighbor_ip }} remote-as 27651
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].neighbor_ip }} route-map MPLS-RESPALDO-{{ vrf_name }} out
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in
      when: 
        - site == 'CDLV' 
        - inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'
        - "'not found' in vlan_check.stdout[0]"
        - vrf_check.stdout[0] == ''
        - prefix_check.stdout[0] == ''
        - routemap_check.stdout[0] == ''    
        - routemap_check_resp.stdout[0] == ''
        - po_check_cdlv_b.stdout[0] == '' 
      changed_when: true
  rescue:
    - name: Mostrar debug del porqué no se ejecutó la tarea
      debug:
        msg: >
          La tarea no se ejecutó porque:
          site = {{ site }},
          inventory_hostname = {{ inventory_hostname }},
          vlan_check.stdout = {{ vlan_check.stdout }},
          vrf_check.stdout = {{ vrf_check.stdout }},
          prefix_check.stdout = {{ prefix_check.stdout }},
          routemap_check.stdout = {{ routemap_check.stdout }},
          routemap_check_resp.stdout = {{ routemap_check_resp.stdout }},
          po_check_cdlv_b.stdout = {{ po_check_amu_b.stdout }}
          
    - name: Configurar MPLS OSPF SVI ROUTE-MAP en AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }}
          
          - vlan {{ vlan_id }}
          - name INTER-RED-TDS-{{ vrf_name }}
          
          - interface {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].ip_po }}
          - no shutdown
          
          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}
          
          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].metric }}
          
          - router ospf {{ ospf_process_id }} vrf {{ vrf_name }}
          - router-id {{ first_ip }}
          - redistribute bgp route-map {{ vrf_name }}-TO-OSPF
          - network {{ network }} area {{ area }}
          
          - interface vlan {{ vlan_id }}
          - description INTER-RED-TDS-{{ vrf_name }}
          - vrf {{ vrf_name }}
          - ip address {{ first_ip }}/29
          - no shutdown
          
          - router bgp {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].router_id }} 
          - neighbor {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].neighbor_ip }} remote-as 27651
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in    
      when: 
        - site == 'AMU' 
        - inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'
        - "'not found' in vlan_check.stdout[0]"
        - vrf_check.stdout[0] == ''
        - prefix_check.stdout[0] == ''
        - routemap_check.stdout[0] == ''    
        - routemap_check_resp.stdout[0] == ''
        - po_check_amu_a.stdout[0] == ''       
      changed_when: true
  rescue:
    - name: Mostrar debug del porqué no se ejecutó la tarea
      debug:
        msg: >
          La tarea no se ejecutó porque:
          site = {{ site }},
          inventory_hostname = {{ inventory_hostname }},
          vlan_check.stdout = {{ vlan_check.stdout }},
          vrf_check.stdout = {{ vrf_check.stdout }},
          prefix_check.stdout = {{ prefix_check.stdout }},
          routemap_check.stdout = {{ routemap_check.stdout }},
          routemap_check_resp.stdout = {{ routemap_check_resp.stdout }},
          po_check_amu_a.stdout = {{ po_check_amu_b.stdout }}
          
    - name: Configurar MPLS OSPF SVI ROUTE-MAP en AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          
          - vlan {{ vlan_id }}
          - name INTER-RED-TDS-{{ vrf_name }}
          
          - interface {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].ip_po }}
          
          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}
          
          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].metric }}
          
          - route-map MPLS-RESPALDO-{{ vrf_name }} permit 10
          - set as-path prepend {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].as_path_prepend }}
          
          - router ospf {{ ospf_process_id }} vrf {{ vrf_name }}
          - router-id {{ second_ip }}
          - redistribute bgp route-map {{ vrf_name }}-TO-OSPF
          - network {{ network }} area {{ area }}
          
          - interface vlan {{ vlan_id }}
          - description INTER-RED-TDS-{{ vrf_name }}
          - vrf {{ vrf_name }}
          - ip address {{ second_ip }}/29
          - no shutdown
          
          - router bgp {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].router_id }} 
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} remote-as 27651
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} route-map MPLS-RESPALDO-{{ vrf_name }} out
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in
      when: 
        - site == 'AMU' 
        - inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'
        - "'not found' in vlan_check.stdout[0]"
        - vrf_check.stdout[0] == ''
        - prefix_check.stdout[0] == ''
        - routemap_check.stdout[0] == ''    
        - routemap_check_resp.stdout[0] == ''
        - po_check_amu_b.stdout[0] == ''   
      changed_when: true
  rescue:
    - name: Mostrar debug del porqué no se ejecutó la tarea
      debug:
        msg: >
          La tarea no se ejecutó porque:
          site = {{ site }},
          inventory_hostname = {{ inventory_hostname }},
          vlan_check.stdout = {{ vlan_check.stdout }},
          vrf_check.stdout = {{ vrf_check.stdout }},
          prefix_check.stdout = {{ prefix_check.stdout }},
          routemap_check.stdout = {{ routemap_check.stdout }},
          routemap_check_resp.stdout = {{ routemap_check_resp.stdout }},
          po_check_amu_b.stdout = {{ po_check_amu_b.stdout }}
            
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
