---
- name: Configurar BGP en el dispositivo Arista
  hosts: all
  gather_facts: no

  vars:
    vrf_name: ""               # Reemplazar con el nombre de la VRF
    router_id: ""              # Reemplazar con el Router ID
    neighbor_ip: ""            # Reemplazar con la IP del vecino BGP
    network: ""                # Reemplazar con la red a anunciar
    filtro_in_bgp: ""          # Reemplazar con el nombre del filtro de prefijos BGP

  tasks:
    - name: Configurar BGP
      arista.eos.eos_command:
        commands:
          - enable
          - configure terminal
          - router bgp 65021
          - bgp log-neighbor-changes
          - vrf {{ vrf_name }}
          - router-id {{ router_id }}
          - neighbor {{ neighbor_ip }} remote-as 27651
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ neighbor_ip }} prefix-list {{ filtro_in_bgp }} in
      register: bgp_config_result
      changed_when: true
      failed_when: false

    - name: Debug Configurar BGP
      debug:
        msg: "Resultado de la configuración de BGP: {{ bgp_config_result }}"

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
