---
- name: Comprobar y crear VLAN en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    vlan_id: ""
    nom_vlan: ""
  
  # Tareas
  tasks:
    - name: Verificar existencia de la VLAN
      arista.eos.eos_command:
        commands:
          - show vlan id {{ vlan_id }}
      register: vlan_check

    # Salida por pantalla
    - name: Mostrar resultado del comando show vlan id
      debug:
        msg: "{{ vlan_check.stdout }}"

    - name: Crear la VLAN si no existe
      arista.eos.eos_config:
        lines:
          - vlan {{ vlan_id }}
          - name {{ nom_vlan }}
      when: "'not found' in vlan_check.stdout[0]"
    
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
        
    - name: Verificar existencia de la VLAN nuevamente
      arista.eos.eos_command:
        commands:
          - show vlan id {{ vlan_id }}
      register: vlan_check_new

    - name: Mostrar resultado del comando show vlan id después de crear la VLAN
      debug:
        msg: "{{ vlan_check_new.stdout }}"

