---
- name: Comprobar y crear route-map en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_route_map: ""
    nom_prefix: ""
    metric: ""
    
  tasks:
    - name: Obtener configuración actual del Route-Map
      eos_command:
        commands:
          - "show running-config section route-map"
      register: route_map_config

    - name: Validar existencia del Route-Map
      set_fact:
        route_map_exists: "{{ route_map_config.stdout[0] is search('route-map {{ nom_route_map }}') }}"

    - name: Configurar Route-Map si no existe
      eos_config:
        lines:
          - "route-map {{ nom_route_map }} permit 10"
          - "match ip address prefix-list {{ nom_prefix }}"
          - "set metric {{ metric }}"
        when: not route_map_exists
      notify: save_config

  handlers:
    - name: Guardar configuración
      eos_command:
        commands:
          - "write memory"
