---
- name: Comprobar y crear route-map en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_route_map: ""
    nom_prefix: ""
    metric: ""
  
  # Tareas
  tasks:
    - name: Verificar existencia del route-map
      arista.eos.eos_command:
      commands: 
       - show running-config | include route-map {{ nom_route_map }}
      register: route_map_output
      changed_when: false
    # Salida por pantalla
    - name: Mostrar resultado del comando show route-map
      debug:
        msg: "{{ nom_route_map.stdout }}"
          
    - name: Crear route-map si no existe
      arista.eos.eos_config:
        lines:
          - " route-map {{ nom_route_map }} permit 10"
          - " match ip address prefix-list {{ nom_prefix }}"
        save_when: modified
      when: route_map_output.stdout == ""

        

