- name: eliminar vlan svi-vrrp y rutas
  hosts: all
  gather_facts: no

  vars:
    site: ""
    vlan_id: ""

  tasks:

    - name: Verificar existencia de la VLAN
      arista.eos.eos_command:
        commands:
          - show vlan id {{ vlan_id }}
      register: vlan_check

    - name: Debug VLAN check
      debug:
        var: vlan_check.stdout

    - name: Verificar existencia de VRRP
      arista.eos.eos_command:
        commands:
          - show vrrp group 100 interface vlan {{ vlan_id }}
      register: vrrp_check

    - name: Debug VRRP check
      debug:
        var: vrrp_check.stdout

    - name: Extraer la IP VIP de VRRP
      set_fact:
        vrrp_ip: "{{ (vrrp_check.stdout[0] | regex_search('Virtual IPv4 address is (\\d+\\.\\d+\\.\\d+\\.\\d+)', '\\1')) | first }}"
      when:
        - vrrp_check.stdout is not none
        - vrrp_check.stdout[0] != ''
        - "(site == 'CDLV' and inventory_hostname in ['CDLV-212-G31-UR29-BLEAF-A', 'CDLV-212-G32-UR29-BLEAF-B']) or (site == 'AMU' and inventory_hostname in ['AMU-P5-E4-UR29-BLEAF-A', 'AMU-P5-E3-UR29-BLEAF-B'])"

    - name: Debug IP VIP de VRRP
      debug:
        var: vrrp_ip

    - name: Convertir la IP VIP VRRP a entero y sumar 1
      set_fact:
        vrrp_ip_int: "{{ (vrrp_ip | ansible.utils.ipaddr('int') + 1) | ansible.utils.ipaddr('ipv4') | regex_replace('/32$', '') }}"
      when:
        - "(site == 'CDLV' and inventory_hostname in ['CDLV-212-G31-UR29-BLEAF-A', 'CDLV-212-G32-UR29-BLEAF-B']) or (site == 'AMU' and inventory_hostname in ['AMU-P5-E4-UR29-BLEAF-A', 'AMU-P5-E3-UR29-BLEAF-B'])"

    - name: Mostrar IP GW de TDS
      debug:
        msg: "La IP GW de TDS es {{ vrrp_ip_int }}"
      when:
        - "(site == 'CDLV' and inventory_hostname in ['CDLV-212-G31-UR29-BLEAF-A', 'CDLV-212-G32-UR29-BLEAF-B']) or (site == 'AMU' and inventory_hostname in ['AMU-P5-E4-UR29-BLEAF-A', 'AMU-P5-E3-UR29-BLEAF-B'])"

    - name: Obtener la configuración completa de las rutas estáticas
      arista.eos.eos_command:
        commands: "show running-config | include {{ vrrp_ip_int }}"
      register: static_routes_output
      when:
        - "(site == 'CDLV' and inventory_hostname in ['CDLV-212-G31-UR29-BLEAF-A', 'CDLV-212-G32-UR29-BLEAF-B']) or (site == 'AMU' and inventory_hostname in ['AMU-P5-E4-UR29-BLEAF-A', 'AMU-P5-E3-UR29-BLEAF-B'])"

    - name: Filtrar rutas estáticas con salto GW TDS
      set_fact:
        filtered_static_routes: "{{ static_routes_output.stdout[0].split('\n') | select('search', vrrp_ip_int) | list }}"
      when:
        - "(site == 'CDLV' and inventory_hostname in ['CDLV-212-G31-UR29-BLEAF-A', 'CDLV-212-G32-UR29-BLEAF-B']) or (site == 'AMU' and inventory_hostname in ['AMU-P5-E4-UR29-BLEAF-A', 'AMU-P5-E3-UR29-BLEAF-B'])"

    - name: Separar rutas estáticas en variables
      set_fact:
        static_route_1: "{{ filtered_static_routes[0] | default('') }}"
        static_route_2: "{{ filtered_static_routes[1] | default('') }}"
        static_route_3: "{{ filtered_static_routes[2] | default('') }}"
        static_route_4: "{{ filtered_static_routes[3] | default('') }}"
        static_route_5: "{{ filtered_static_routes[4] | default('') }}"
        static_route_6: "{{ filtered_static_routes[5] | default('') }}"
        static_route_7: "{{ filtered_static_routes[6] | default('') }}"
        static_route_8: "{{ filtered_static_routes[7] | default('') }}"
        static_route_9: "{{ filtered_static_routes[8] | default('') }}"
        static_route_10: "{{ filtered_static_routes[9] | default('') }}"

    - name: Debug rutas estáticas separadas
      debug:
        msg:
        - "Ruta 1: {{ static_route_1 }}"
        - "Ruta 2: {{ static_route_2 }}"
        - "Ruta 3: {{ static_route_3 }}"
        - "Ruta 4: {{ static_route_4 }}"
        - "Ruta 5: {{ static_route_5 }}"
        - "Ruta 6: {{ static_route_6 }}"
        - "Ruta 7: {{ static_route_7 }}"
        - "Ruta 8: {{ static_route_8 }}"
        - "Ruta 9: {{ static_route_9 }}"
        - "Ruta 10: {{ static_route_10 }}"

    - name: Eliminar SVI de VLAN
      arista.eos.eos_command:
        commands:
          - configure terminal
          - no interface vlan {{ vlan_id }}
          - no vlan {{ vlan_id }}
      when:
        - "'not found' not in vlan_check.stdout[0]"
        - vrrp_check.stdout[0] != ''
        - "(site == 'CDLV' and inventory_hostname in ['CDLV-212-G31-UR29-BLEAF-A', 'CDLV-212-G32-UR29-BLEAF-B']) or (site == 'AMU' and inventory_hostname in ['AMU-P5-E4-UR29-BLEAF-A', 'AMU-P5-E3-UR29-BLEAF-B'])"
      changed_when: true

    - name: Eliminar rutas estáticas
      arista.eos.eos_command:
        commands:
          - "no {{ item }}"
      loop:
        - "{{ static_route_1 }}"
        - "{{ static_route_2 }}"
        - "{{ static_route_3 }}"
        - "{{ static_route_4 }}"
        - "{{ static_route_5 }}"
        - "{{ static_route_6 }}"
        - "{{ static_route_7 }}"
        - "{{ static_route_8 }}"
        - "{{ static_route_9 }}"
        - "{{ static_route_10 }}"
      when:
        - item != ''
        - "'not found' not in vlan_check.stdout[0]"
        - vrrp_check.stdout[0] != ''
        - "(site == 'CDLV' and inventory_hostname in ['CDLV-212-G31-UR29-BLEAF-A', 'CDLV-212-G32-UR29-BLEAF-B']) or (site == 'AMU' and inventory_hostname in ['AMU-P5-E4-UR29-BLEAF-A', 'AMU-P5-E3-UR29-BLEAF-B'])"
      changed_when: true

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory

