- name: Crear PREFIX-LIST switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_prefix: ""
    prefix_1: ""
    prefix_2: ""
    prefix_3: ""
    prefix_4: ""
    prefix_5: ""
    prefix_6: ""
    prefix_7: ""
    prefix_8: ""
    prefix_9: ""
    prefix_10: ""
    prefix_list:
      - "{{ prefix_1 }}"
      - "{{ prefix_2 }}"
      - "{{ prefix_3 }}"
      - "{{ prefix_4 }}"
      - "{{ prefix_5 }}"
      - "{{ prefix_6 }}"
      - "{{ prefix_7 }}"
      - "{{ prefix_8 }}"
      - "{{ prefix_9 }}"
      - "{{ prefix_10 }}"
  
  # Tareas
  tasks:
    - name: Crea PREFIX-LIST
      arista.eos.eos_config:
        lines: |
          ip prefix-list {{ nom_prefix }}
          {% for prefix in prefix_list %}
          {% if prefix != '' %}
          permit {{ prefix }}
          {% endif %}
          {% endfor %}
      when: prefix_list | select('defined') | select('ne', '') | list | length > 0
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
        
    - name: Verificar PREFIX creado
      arista.eos.eos_command:
        commands:
          - show running-config | sec prefix
      register: prefix_check_new

    - name: Mostrar resultado del comando show running-config | sec prefix
      debug:
        msg: "{{ prefix_check_new.stdout }}"
