---
- name: rollback de configuracion CREAR_MPLS_ESC
  hosts: switches
  gather_facts: no
  
  vars:
    vrf_name: ""
  
  tasks:
    - name: Verificar existencia de la VRF
      arista.eos.eos_command:
        commands:
          - show vrf | include {{ vrf_name }}
      register: vrf_check
      
    - name: Debug VRF check
      debug:
        var: vrf_check.stdout
        
    - name: Obtener la configuración
      arista.eos.eos_command:
        commands:
          - show running-config section {{ vrf_name }}
      register: vrf_config

    - name: Extraer VLAN ID
      set_fact:
        vlan_id: "{{ vrf_config.stdout[0] | regex_search('vlan (\\d+)', '\\1') }}"

    - name: Extraer Port-Channel
      set_fact:
        port_channel: "{{ vrf_config.stdout[0] | regex_search('interface (Port-Channel\\d+\\.\\d+)', '\\1') }}"

    - name: Extraer VLAN interface
      set_fact:
        vlan_interface: "{{ vrf_config.stdout[0] | regex_search('interface Vlan(\\d+)', 'Vlan\\1') }}"

    - name: Extraer prefix-list name
      set_fact:
        prefix_list: "{{ vrf_config.stdout[0] | regex_search('ip prefix-list (\\S+)', '\\1') }}"

    - name: Extraer route-map name
      set_fact:
        route_map: "{{ vrf_config.stdout[0] | regex_search('route-map (\\S+)', '\\1') }}"

    - name: Extraer el ID de OSPF para la VRF
      set_fact:
        ospf_id: "{{ vrf_config.stdout[0] | regex_search('router ospf (\\d+) vrf {{ vrf_name }}', '\\1') }}"

    - name: Eliminar toda la configuración 
      arista.eos.eos_config:
        lines:
          - "no vlan {{ vlan_id }}"
          - "no vrf definition {{ vrf_name }}"
          - "no interface {{ port_channel }}"
          - "no interface {{ vlan_interface }}"
          - "no ip prefix-list {{ prefix_list }}"
          - "no route-map {{ route_map }}"
          - "router bgp 65121"
          - "no vrf {{ vrf_name }}"
          - "no router ospf {{ ospf_id }} vrf {{ vrf_name }}"
      when: 
       - vrf_check.stdout[0] != ''
      changed_when: true
      
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory

