---
- name: Comprobar y crear route-map en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_route_map: ""
    nom_prefix: ""
    metric: ""

  tasks:
    - name: Verificar si el route-map ya existe
      arista.eos.eos_command:
        commands: "show running-config | include route-map {{ nom_route_map }}"
      register: route_map_check
      ignore_errors: yes

    - name: Mostrar salida del chequeo del route-map
      debug:
        msg: "Salida del chequeo del route-map: {{ route_map_check.stdout_lines }}"

    - name: Configurar route-map
      arista.eos.eos_config:
        lines:
          - "route-map {{ nom_route_map }} permit 10"
          - " match ip address prefix-list {{ nom_prefix }}"
          - " set metric {{ metric }}"
        save_when: modified

    - name: Mostrar mensaje de que el route-map fue configurado
      debug:
        msg: "Route-map '{{ nom_route_map }}' ha sido configurado con el prefijo '{{ nom_prefix }}' y métrica '{{ metric }}'."
