---
- name: Comprobar y crear route-map en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_route_map: ""
    nom_prefix: ""
    metric: ""
    
  tasks:
    - name: Obtener configuración actual del Route-Map
      arista.eos.eos_command:
        commands:
          - "show running-config | include route-map {{ nom_route_map }}"
      register: route_map_config

    - name: Debug de la configuración actual del Route-Map
      debug:
        msg: "Configuración actual del Route-Map: {{ route_map_config.stdout }}"

    - name: Configurar Route-Map si no existe
      arista.eos.eos_command:
        commands:
          - "configure terminal"
          - "route-map {{ nom_route_map }} permit 10"
          - "match ip address prefix-list {{ nom_prefix }}"
          - "set metric {{ metric }}"
      when: route_map_config.stdout == ""
      register: route_map_configured

    - name: Informar si se realizó la configuración del Route-Map
      debug:
        msg: "Configuración del Route-Map realizada"
      when: route_map_configured is defined and route_map_configured.changed

    - name: Informar si no se realizó la configuración del Route-Map
      debug:
        msg: "El Route-Map ya existía, no se realizó ninguna configuración"
      when: route_map_configured is not defined or not route_map_configured.changed

    - name: Guardar configuración
      arista.eos.eos_command:
        commands:
          - "write memory"
      when: route_map_configured is defined and route_map_configured.changed
