---
- name: Crear PREFIX-LIST switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_prefix: ""
    id_prefix_1: ""
    prefix_1: ""
    id_prefix_2: ""
    prefix_2: ""
    id_prefix_3: ""
    prefix_3: ""
    id_prefix_4: ""
    prefix_4: ""
    id_prefix_5: ""
    prefix_5: ""
    id_prefix_6: ""
    prefix_6: ""
    id_prefix_7: ""
    prefix_7: ""
    id_prefix_8: ""
    prefix_8: ""
    id_prefix_9: ""
    prefix_9: ""
    id_prefix_10: ""
    prefix_10: ""
    prefix_list:
      - id: "{{ id_prefix_1 }}"
        prefix: "{{ prefix_1 }}"
      - id: "{{ id_prefix_2 }}"
        prefix: "{{ prefix_2 }}"
      - id: "{{ id_prefix_3 }}"
        prefix: "{{ prefix_3 }}"
      - id: "{{ id_prefix_4 }}"
        prefix: "{{ prefix_4 }}"
      - id: "{{ id_prefix_5 }}"
        prefix: "{{ prefix_5 }}"
      - id: "{{ id_prefix_6 }}"
        prefix: "{{ prefix_6 }}"
      - id: "{{ id_prefix_7 }}"
        prefix: "{{ prefix_7 }}"
      - id: "{{ id_prefix_8 }}"
        prefix: "{{ prefix_8 }}"
      - id: "{{ id_prefix_9 }}"
        prefix: "{{ prefix_9 }}"
      - id: "{{ id_prefix_10 }}"
        prefix: "{{ prefix_10 }}"
  
  # Tareas
  tasks:
    - name: Verificar PREFIX-LIST en switch
      arista.eos.eos_command:
        commands:
          - show running-config | sec prefix
      register: prefix_check

    # Salida por pantalla
    - name: Mostrar resultado del comando show running-config | sec prefix
      debug:
        msg: "{{ prefix_check.stdout }}"

    - name: Crea PREFIX-LIST
      arista.eos.eos_config:
        lines: |
          ip prefix-list {{ nom_prefix }}
          {% for item in prefix_list %}
          {% if item.id and item.prefix %}
          seq {{ item.id }} permit {{ item.prefix }}
          {% endif %}
          {% endfor %}
      when: prefix_list | selectattr('id', 'defined') | selectattr('prefix', 'defined') | list | length > 0
    
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
        
    - name: Verificar PREFIX creado
      arista.eos.eos_command:
        commands:
          - show running-config | sec prefix
      register: prefix_check_new

    - name: Mostrar resultado del comando show running-config | sec prefix
      debug:
        msg: "{{ prefix_check_new.stdout }}"
