- name: eliminar vlan svi-vrrp y rutas
  hosts: all
  gather_facts: no

  vars:
    site: ""
    vlan_id: ""

  tasks:

    - name: Verificar existencia de la VLAN 
      arista.eos.eos_command:
        commands:
          - show vlan id {{ vlan_id }}
      register: vlan_check

    - name: Debug VLAN check
      debug:
        var: vlan_check.stdout

    - name: Verificar existencia de vrrp
      arista.eos.eos_command:
        commands:
          - show vrrp group 100 interface vlan {{ vlan_id }}
      register: vrrp_check

    - name: Debug VRRP check
      debug:
        var: vrrp_check.stdout

    - name: Extraer las IP VIP de VRRP
      set_fact:
        vrrp_ip: "{{ vrrp_check.stdout[0] | regex_search('vrrp 100 ipv4 (\\d+\\.\\d+\\.\\d+\\.\\d+)') }}"

    - name: Convertir la IP VIP VRRP a entero y sumar 1
      set_fact:
        vrrp_ip_int: "{{ (vrrp_ip | ipaddr('int') + 1) | ipaddr('ipv4') }}"

    - name: Mostrar nueva IP GW de TDS
      debug:
        msg: "La nueva IP es {{ vrrp_ip_int }}"
      
    - name: Obtener la configuración completa de las rutas estáticas
      arista.eos.eos_command:
        commands: "show running-config | include {{ vrrp_ip_int }}"
      register: static_routes_output

    - name: Mostrar la configuración completa de las rutas estáticas
      debug:
        var: static_routes_output.stdout

    - name: Generar comandos para eliminar rutas estáticas
      set_fact:
        delete_commands: >
          {{
            static_routes_output.stdout[0].splitlines() | select("search", vrrp_ip_int) |
            map("regex_replace", "^", "no ") | list
          }}

    - name: Ejecutar los comandos para eliminar las rutas estáticas
      arista.eos.eos_command:
        commands: "{{ delete_commands }}"

    - name: Configurar VRRP y Ruta Estatica Publica en CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - no interface vlan {{ vlan_id }}
          - no vlan {{ vlan_id }}
          - "{{ delete_commands | join('\n') }}"
      when: 
        - site == 'CDLV' 
        - inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'
        - "'not found' not in vlan_check.stdout[0]"
        - vrrp_check.stdout[0] != ''
      changed_when: true

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
