---
- name: Comprobar y crear route-map en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_route_map: ""
    nom_prefix: ""
    metric: ""
  
  tasks:
    - name: Verificar si el route-map ya existe
      arista.eos.eos_command:
        commands: "show run section route-map | include {{ nom_route_map }}"
      register: route_map_output
      changed_when: false

    - name: Crear route-map si no existe
      arista.eos.eos_config:
        lines:
         - route-map {{ nom_route_map }} permit 10
         - match ip address prefix-list {{ nom_prefix }}
         - set metric {{ metric }}
      when: route_map_output.stdout == ""

