- name: crear mpls, vrf, ospf, bgp
  hosts: all
  gather_facts: no

  vars:
    site: ""
    vlan_po: ""
    vlan_id: ""
    segmento: ""
    vrf_name: ""
    network: ""
    prefix_in: ""
    equipos_config:
      AMU-P5-E4-UR29-BLEAF-A:
        bgp_asn: "65021"
        neighbor_ip: "169.254.196.9"
        router_id: "169.254.196.10"
        id_po: "Port-Channel5."
        ip_po: "169.254.196.10/30"
        metric: "30000"
      AMU-P5-E3-UR29-BLEAF-B:
        bgp_asn: "65021"
        neighbor_ip: "169.254.196.13"
        router_id: "169.254.196.14"
        id_po: "Port-Channel6."
        ip_po: "169.254.196.14/30"
        as_path_prepend: "65021"
        metric: "40000"
      CDLV-212-G31-UR29-BLEAF-A:
        bgp_asn: "65121"
        neighbor_ip: "169.254.196.17"
        router_id: "169.254.196.18"
        id_po: "Port-Channel5."
        ip_po: "169.254.196.18/30"
        metric: "10000"
      CDLV-212-G32-UR29-BLEAF-B:
        bgp_asn: "65121"
        neighbor_ip: "169.254.196.21"
        router_id: "169.254.196.22"
        id_po: "Port-Channel6."
        ip_po: "169.254.196.22/30"
        as_path_prepend: "65121"
        metric: "20000"

  tasks:
  
    - name: Verificar existencia de la VRF
      arista.eos.eos_command:
        commands:
          - show vrf | in {{ vrf_name }}
      register: vrf_check


      

    - name: Verificar existencia de la prefix-list
      arista.eos.eos_command:
        commands:
          - show running-config section ip prefix-list | i {{ vrf_name }}-ESC-TO-BGP-IN
      register: prefix_check


    - name: Verificar existencia del route-map
      arista.eos.eos_command:
        commands:
          - show running-config section route-map | i {{ vrf_name }}-TO-OSPF
      register: routemap_check

    - name: Verificar existencia del route-map
      arista.eos.eos_command:
        commands:
          - show running-config section route-map | i MPLS-RESPALDO-{{ vrf_name }}
      register: routemap_check_resp
      

    - name: Verificar existencia del port-channel en equipo CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
      register: po_check_cdlv_a
      when: site == 'CDLV' and inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'

    - name: Verificar existencia del port-channel en equipo CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
      register: po_check_cdlv_b
      when: site == 'CDLV' and inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'

    - name: Verificar existencia del port-channel en equipo AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
      register: po_check_amu_a
      when: site == 'AMU' and inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'

    - name: Verificar existencia del port-channel en equipo AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - show ip int brief | i {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
      register: po_check_amu_b
      when: site == 'AMU' and inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'

  
    - name: Configurar la interfaz para equipo CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          
          - interface {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].ip_po }}

          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}

          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].metric }}
          
          - router bgp {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].router_id }} 
          - neighbor {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].neighbor_ip }} remote-as 27651
          
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['CDLV-212-G31-UR29-BLEAF-A'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in
      when: site == 'CDLV' and "'' in vrf_check.stdout[0]" and "'' in po_check_cdlv_a[0]" and "'' in prefix_check[0]" and "'' in routemap_check[0]" and "'' in routemap_check_resp[0]" and inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A'


    - name: Configurar la interfaz para equipo CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          
          - interface {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].ip_po }}

          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}

          - route-map MPLS-RESPALDO-{{ vrf_name }} permit 10
          - set as-path prepend {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].as_path_prepend }}

          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].metric }}
          
          - router bgp {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].router_id }} 
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].neighbor_ip }} remote-as 27651
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].neighbor_ip }} route-map MPLS-RESPALDO-{{ vrf_name }} out
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in
      when: site == 'CDLV' and "'' in vrf_check.stdout[0]" and "'' in po_check_cdlv_b[0]" and "'' in prefix_check[0]" and "'' in routemap_check[0]" and "'' in routemap_check_resp[0]" and inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'


    - name: Configurar la interfaz para equipo AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          - interface {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].ip_po }}

          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}

          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].metric }}
          
          - router bgp {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].router_id }} 
          - neighbor {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].neighbor_ip }} remote-as 27651
          
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in


          
      when: site == 'AMU' and "'' in vrf_check.stdout[0]" and "'' in po_check_amu_a[0]" and "'' in prefix_check[0]" and "'' in routemap_check[0]" and "'' in routemap_check_resp[0]" and inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'

    - name: Configurar la interfaz para equipo AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_command:
        commands:
          - configure terminal
          - vrf instance {{ vrf_name }}
          - ip routing vrf {{ vrf_name }} 
          - interface {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ vlan_id }}
          - description {{ vrf_name }}MPLS
          - encapsulation dot1q vlan {{ vlan_id }}
          - no shutdown
          - vrf {{ vrf_name }}
          - ip address {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].ip_po }}

          - ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN permit {{ prefix_in }}

          - route-map {{ vrf_name }}-TO-OSPF permit 10
          - match ip address prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - set metric {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].metric }}
          
          - route-map MPLS-RESPALDO-{{ vrf_name }} permit 10
          - set as-path prepend {{ equipos_config['CDLV-212-G32-UR29-BLEAF-B'].as_path_prepend }}
        
          - router bgp {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].bgp_asn }}
          - vrf {{ vrf_name }}
          - router-id {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].router_id }} 
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} remote-as 27651
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} route-map MPLS-RESPALDO-{{ vrf_name }} out
          - network {{ network }}
          - address-family ipv4
          - neighbor {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].neighbor_ip }} prefix-list {{ vrf_name }}-ESC-TO-BGP-IN in
          
      when: site == 'AMU' and "'' in vrf_check.stdout[0]" and "'' in po_check_amu_b[0]" and "'' in prefix_check[0]" and "'' in routemap_check[0]" and "'' in routemap_check_resp[0]" and inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'

    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory
