- name: Rollback basado en ID de Job en Ansible Tower
  hosts: all
  gather_facts: no
  vars_prompt:
    - name: job_id
      private: no

  tasks:

    - name: Obtener detalles del job ejecutado
      awx.awx.tower_job_list:
        id: "{{ job_id }}"
      register: job_details

    - name: Obtener variables utilizadas en el job
      set_fact:
        job_vars: "{{ job_details.json.extra_vars }}"

    - name: Debug de variables obtenidas del job
      debug:
        var: job_vars

    - name: Eliminar configuraciones de BGP, OSPF, SVI, Route-map en equipo {{ inventory_hostname }}
      arista.eos.eos_command:
        commands:
          - configure terminal
          - no router bgp {{ job_vars.equipos_config[inventory_hostname].bgp_asn }} vrf {{ job_vars.vrf_name }}
          - no router ospf vrf {{ job_vars.vrf_name }}
          - no route-map {{ job_vars.vrf_name }}-TO-OSPF
          - no ip prefix-list {{ job_vars.vrf_name }}-ESC-TO-BGP-IN
          - no vlan {{ job_vars.vlan_id }}
          - no vrf instance {{ job_vars.vrf_name }}
          - interface {{ job_vars.equipos_config[inventory_hostname].id_po }}{{ job_vars.vlan_id }}
          - no ip address
          - no shutdown
          - default interface {{ job_vars.equipos_config[inventory_hostname].id_po }}{{ job_vars.vlan_id }}
          - interface vlan {{ job_vars.vlan_id }}
          - no ip address
          - no vrf {{ job_vars.vrf_name }}
          - shutdown
          - default interface vlan {{ job_vars.vlan_id }}
          - no interface vlan {{ job_vars.vlan_id }}
          - write memory
      when: 
        - job_vars.site == 'AMU' and (inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A' or inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B')
        - job_vars.site == 'CDLV' and (inventory_hostname == 'CDLV-212-G31-UR29-BLEAF-A' or inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B')
