---
- name: Comprobar y crear route-map en el switch Arista
  hosts: all
  gather_facts: no
  
  # Variables
  vars:
    nom_route_map: ""
    nom_prefix: ""
    metric: ""
  # Tareas
  tasks:
    - name: Verificar existencia del route-map
      arista.eos.eos_command:
        commands:
          - command: "show running-config section route-map"
      register: route_map_config

    - name: Configurar el route-map si no existe
      arista.eos.eos_command:
        commands:
          - command: |
              route-map {{ route_map_name }} permit 10
              match ip address prefix-list {{ prefix }}
              set metric {{ metric }}
      when: route_map_config.stdout is search("route-map {{ route_map_name }} permit 10") == false

    - name: Validar configuración del route-map
      arista.eos.eos_command:
        commands:
          - command: "show running-config | include route-map {{ route_map_name }}"
      register: validation_output

    - name: Mostrar resultado de la validación
      debug:
        msg: "{{ validation_output.stdout }}"
