---
- name: rollback de configuracion CREAR_MPLS_ESC
  hosts: all
  gather_facts: no
  
  vars:
    vrf_name: ""
    site: ""
    
  
  tasks:


    - name: Eliminar configuraciones relacionadas para CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_config:
        commands:
          - configure terminal
          - router bgp 65121
          - no vrf {{ vrf_name }}
      when: 
        - site == 'CDLV' 
        - inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'
      changed_when: true

    - name: Eliminar configuraciones relacionadas para CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_config:
        commands:
          - configure terminal
          - router bgp 65121
          - no vrf {{ vrf_name }}
      when: 
          - site == 'CDLV' 
          - inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'
      changed_when: true

  

    - name: Eliminar toda la configuración para AMU-P5-E4-UR29-BLEAF-A
      arista.eos.eos_config:
        commands:
          - configure terminal
          - router bgp 65021
          - no vrf {{ vrf_name }}
          - interface Port-Channel 12
          - switchport trunk allowed vlan remove {{ vlan_id }}
          - no ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - no route-map {{ vrf_name }}-TO-OSPF
          - no router ospf {{ ospf_instance_id }} vrf {{ vrf_name }}
          - no interface vlan {{ vlan_id }}
          - no interface {{ equipos_config['AMU-P5-E4-UR29-BLEAF-A'].id_po }}{{ port_channel }}
          - no vlan {{ vlan_id }}
          - no vrf instance {{ vrf_name }}
      when: 
       - vrf_check.stdout[0] != ''
       - site == 'AMU' 
       - inventory_hostname == 'AMU-P5-E4-UR29-BLEAF-A'
      changed_when: true

    - name: Eliminar toda la configuración para AMU-P5-E3-UR29-BLEAF-B
      arista.eos.eos_config:
        commands:
          - configure terminal
          - configure terminal
          - router bgp 65021
          - no vrf {{ vrf_name }}
          - interface Port-Channel 12
          - switchport trunk allowed vlan remove {{ vlan_id }}
          - no ip prefix-list {{ vrf_name }}-ESC-TO-BGP-IN
          - no route-map {{ vrf_name }}-TO-OSPF
          - no route-map MPLS-RESPALDO-{{ vrf_name }} 
          - no router ospf {{ ospf_instance_id }} vrf {{ vrf_name }}
          - no interface vlan {{ vlan_id }}   
          - no interface {{ equipos_config['AMU-P5-E3-UR29-BLEAF-B'].id_po }}{{ port_channel }}
          - no vlan {{ vlan_id }}
          - no vrf instance {{ vrf_name }}
      when: 
       - vrf_check.stdout[0] != ''
       - site == 'AMU' 
       - inventory_hostname == 'AMU-P5-E3-UR29-BLEAF-B'
      changed_when: true
    
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory

    - name: Debug guardado de cambios
      debug:
        msg: "Cambios guardados en el dispositivo."

