---
- name: "[PLAY-1] [CUSTOM CREDENTIAL POC] - ENTEL - Prueba de Credencial Custom - V1"
  hosts: localhost
  become: False
  gather_facts: True

  vars:
    extra_debug: True
   

  pre_tasks:

  - name: "[INFO] [CUSTOM CREDENTIAL POC] VALIDATION -> CUSTOM CREDENTIAL VARIABLES"
    ansible.builtin.assert:
      that:
        - ansible_facts['env']['ENTEL_API_HOST'] is defined
        - ansible_facts['env']['ENTEL_API_HOST'] != ""
        - ansible_facts['env']['ENTEL_API_TOKEN'] is defined
        - ansible_facts['env']['ENTEL_API_TOKEN'] != ""


  tasks:

  - ansible.builtin.debug: 
      msg: "INFO: [CUSTOM CREDENTIAL POC] PRINT VARIABLE 'ENTEL_API_HOST' -> {{ ansible_facts['env']['ENTEL_API_HOST'] }}"

  - ansible.builtin.debug: 
      msg: "INFO: [CUSTOM CREDENTIAL POC] PRINT VARIABLE 'ENTEL_API_TOKEN' -> {{ ansible_facts['env']['ENTEL_API_TOKEN'] }}"
