---
- name: rollback de configuracion CREAR_MPLS_ESC
  hosts: all
  gather_facts: no
  
  vars:
    vrf_name: ""
    site: ""
    
  
  tasks:


    - name: Eliminar configuraciones relacionadas para CDLV-212-G31-UR29-BLEAF-A
      arista.eos.eos_config:
        commands:
          - configure terminal
          - router bgp 65121
          - no vrf {{ vrf_name }}
      when: 
        - site == 'CDLV' 
        - inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'
      changed_when: true

    - name: Eliminar configuraciones relacionadas para CDLV-212-G32-UR29-BLEAF-B
      arista.eos.eos_config:
        commands:
          - configure terminal
          - router bgp 65121
          - no vrf {{ vrf_name }}
      when: 
          - site == 'CDLV' 
          - inventory_hostname == 'CDLV-212-G32-UR29-BLEAF-B'
      changed_when: true

  

  
    
    - name: Guardar cambios
      arista.eos.eos_command:
        commands:
          - write memory

    - name: Debug guardado de cambios
      debug:
        msg: "Cambios guardados en el dispositivo."

