---
- name: "[PLAY-01] HELLO ANSIBLE - V1"
  hosts: all
  become: false

  vars:
    variable1: "1000"
    variable2: "AAAAA"
    variable3: "BC202020"

  tasks:

  - ansible.builtin.assert:
      that:
        - variable1 is defined

  - ansible.builtin.debug:
      msg: "VAR2 -> {{ variable2 }}"
...
